.\" Manpage for automydumper.
.TH man 8 "24 Jan 2018" "1.1.0" "automydumper man page"
.SH NAME
automydumper \- Automated MySQL backups using Mydumper
.SH SYNOPSIS
automydumper
.SH DESCRIPTION
Automydumper handles backups, retention and rotation for MySQL, Percona Server and Mariadb servers. It uses Mydumper under the hood.
.PP
To restore, myloader ( part of the Mydumper package ) should be used. See its manpage for more information (`man myloader`).
.SH OPTIONS
The automydumper command does not take any options. It it configured by editing /etc/default/automydumper.
.SH FILES
.TP
/etc/automydumper.cfg
Main configuration file. Uses key=value notation. See VARIABLES chapter in the manpage.
.TP
/usr/bin/automydumper
Wrapper around Mydumper. Main application that handles the actual backing-up and clean of old backups.
.TP
/etc/cron.d/automydumper
Scheduled backup runs by Cron.
.SH VARIABLES
The following variables can be used in /etc/default/automydumper to customize the automydumper application.
.TP
.B backup_root_dir
Top directory where backups will be stored.
.br
Default: /var/backups/automydumper
.TP
.B backup_root_format
Backups will be stored in directies named by the following format. Use `date --help` to see all possible options. When using '/' inside the format, new directories will be created.
.br
Default: +%F
.TP
.B logdir
.br
Directory that contains the log files that are generated on each run.
.br
Default: /var/log/automydumper
.TP
.B compress
Toggle gzip compression of output files. Compression is done on the fly.
.br
Default: 1
.TP
.B keep
Determines how many backups will be kept.
.br
Default: 3
.TP
.B mysql_user
User for MySQL connection.
.br
Default: root
.TP
.B mysql_password
Password for MySQL connection.
.br
Default: empty
.TP
.B mysql_host
Host of MySQL server.
.br
Default: localhost
.TP
.B mysql_socket
Unix socket on which MySQL listens when host is localhost or 127.0.0.1. Leaving this empty will autodetect it through my.cnf ( [client] section ).
.br
Default: empty
.TP
.B threads
Amount of concurrent backup threads that take care of dumping InnoDB data from MySQL. The same amount of threads will be started for non-transactional tables as well.
.br
Default: 4
.TP
.B mydumper_opts
Extra options that will be passed on to mydumper.
.br
Default: empty
.TP
.B enabled
When this is 0, the script will exit immediately and perform no backups or check the retention of older backups.
.br
Default: 1
.TP
.B pre_dir
Directory with optional scripts that will be executed BEFORE the actual backup. If a script fails, the backup will abort. Scripts need to be executable!
.br
Default: empty
.TP
.B post_dir
Directory with optional scripts that will be executed AFTER the actual backup. If the command fails, the backup will abort. Scripts need to be executable!
.br
Default: empty
.TP
.B mail_rcpts
Where to send email reports to. Email addresses should be comma separated, no spaces! Won't send any mails if empty.
.br
Default: empty
.TP
.B mail_from
Sender of the email report.
.br
Default: automydumper@$HOSTNAME
.br
.SH RESTORING BACKUPS
Restoring backups can be done either with myloader, or by manually zcat'ing a table backup to mysql.
.br
Please refer to the myloader man page for more details. Below are some of the mostly-used use-cases.
.TP
Restoring a full MySQL instance ( all databases, all tables ), overwriting existing tables:
.TP
# myloader -d /var/backups/automydumper/2015-12-31/ -o -v 3
.TP
Restoring a single database (db1), overwriting existing tables:
.TP
# myloader -d /var/backups/automydumper/2015-12-31/ -o -v 3 -s db1
.TP
Restoring a single table 't1' from database db1:
.TP
# zcat /var/backups/automydumper/2015-12-31/db1.t1.sql.gz | mysql db1
.br
.SH SEE ALSO
myloader(1), mydumper(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Bart Verwilst (bart@verwilst.be)
