# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "boxcutter/debian82"
  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "automydumper"
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  config.vm.hostname = "automydumper"
  
  config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.sudo = true
  end

  config.vm.synced_folder "../", "/home/vagrant/code", owner: "vagrant", group: "vagrant"
  
end
