#!/bin/bash

set -e

case "$1" in
    configure)

        # Migration to /etc/automydumper.cfg for older versions
        if [ -e /etc/default/automydumper ] ; then
            grep -v ^# /etc/default/automydumper >> /etc/automydumper.cfg
            rm -f /etc/default/automydumper
        fi

        if [ -e /etc/automydumper.cfg ] ; then
            . /etc/automydumper.cfg
        fi

        if [ -f /etc/cron.d/automydumper ]; then
            minute="$(cat /etc/cron.d/automydumper | gawk '/(\s+).*\/usr\/bin\/automydumper/ { print $1 }')"
            hour="$(cat /etc/cron.d/automydumper | gawk '/(\s+).*\/usr\/bin\/automydumper/ { print $2 }')"
        else
            minute="$((RANDOM%59))"
            hour="$((RANDOM%4))"
        fi

        cat <<EOF > /etc/cron.d/automydumper
#
# cron-job for automydumper
#

${minute} ${hour} * * * root /usr/bin/automydumper &> /dev/null
EOF
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
