#!/bin/bash

set -e

case "$1" in
    configure)

        # Migration to /etc/automydumper.cfg for older versions
        if [ -e /etc/default/automydumper ] ; then
            grep -v ^# /etc/default/automydumper >> /etc/automydumper.cfg
            rm -f /etc/default/automydumper
        fi

        if [ -e /etc/automydumper.cfg ] ; then
            . /etc/automydumper.cfg
        fi

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
